In [1]:
import numpy as np
import cv2

width = 200
height = 100
value = 128

# width=200、height=100、画素値0で埋めたグレースケール画像を生成
img1 = np.zeros((height, width), np.uint8)

# width=200、height=100、画素値128で埋めたグレースケール画像を生成
img2 = np.full((height, width), value, np.uint8)#８ビットの符号なししか使わない宣言


cv2.imshow('img1', img1)
cv2.imshow('img2', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
import numpy as np
import cv2

width = 200
height = 100
channels = 3
value = (0, 0, 255) # 画素値(B=0, G=0, R=255)

# width=200、height=100、3チャンネルとも画素値0で埋めたカラー画像を生成
img1 = np.zeros((height, width, channels), np.uint8)

# width=200、height=100、画素値(B=0, G=0, R=255)で埋めたカラー画像を生成
img2 = np.full((height, width, channels), value, np.uint8)

# 画像をウィンドウ表示する
cv2.imshow('img1', img1)
cv2.imshow('img2', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
import numpy as np
import cv2

# 画像ファイルをカラーで読み込み
img = cv2.imread('yorkie.png', cv2.IMREAD_COLOR)#カラーで読み込んでね

x = 200
y = 100
channel = 0

bgr_val = img[y, x]
print(f'bgr_val({x}, {y}) = {bgr_val}')

# 0番目のチャンネル（＝Blue）の(x, y) = (200, 100)の画素値を参照
# 座標値指定がy、xの順になっている点に注意
b_val = img[y, x, channel]
print(f'b_val({x}, {y}) = {b_val}')

bgr_val(200, 100) = [ 73 131 104]
b_val(200, 100) = 73


In [4]:
print(img.shape)

(320, 480, 3)


In [5]:
print(img.dtype)

uint8


In [6]:
import cv2

# 画像ファイルをカラーで読み込み
img = cv2.imread('yorkie.png', cv2.IMREAD_COLOR)
x = 200
y = 100
channel = 0

print(f'before: bgr_val({x}, {y}) = {img[y, x]}')

# (x, y) = (200, 100)の画素値を代入（Blue、Green、Redチャンネル）
img[y, x] = [255, 255, 255]
print(f'after: bgr_val({x}, {y}) = {img[y, x]}')

print(f'before: b_val({x}, {y}) = {img[y, x, channel]}')

# 0番目のチャンネル（＝Blueチャンネル）の(x, y) = (200, 100)の画素値を代入
img[y, x, channel] = 0
print(f'after: b_val({x}, {y}) = {img[y, x, channel]}')

before: bgr_val(200, 100) = [ 73 131 104]
after: bgr_val(200, 100) = [255 255 255]
before: b_val(200, 100) = 255
after: b_val(200, 100) = 0


In [7]:
import cv2

# 画像ファイルをカラーで読み込み
img = cv2.imread('yorkie.png', cv2.IMREAD_COLOR)

# ROI[top:bottom, left:right]を使って画像データを切り出す
img_roi = img[135:320, 150:290]#numpyは参照するだけなので、img_roiの変更はimgに反映される
img_roi[10:15, 10:15, :] = [0, 0, 255] 

# 画像をウィンドウ表示する
cv2.imshow('img', img)
cv2.imshow('img_roi', img_roi)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
import numpy as np
import cv2

x = np.uint8([250])
y = np.uint8([5])
z = cv2.add(x, y) # 250 + 5 = 255
print(f'z = {z}')
import numpy as np
import cv2

x = np.uint8([10])
y = np.uint8([20])
z = cv2.subtract(x, y) # 10 - 20 = -10 => 0
print(f'z = {z}')

z = [[255.]
 [  0.]
 [  0.]
 [  0.]]
z = [[-10.]
 [  0.]
 [  0.]
 [  0.]]


In [15]:
import numpy as np
import cv2

x = np.uint8([10])
y = np.uint8([20])
z = cv2.subtract(x, y) # 10 - 20 = -10 => 0
print(z)

[[-10.]
 [  0.]
 [  0.]
 [  0.]]


In [ ]:
import cv2

# 画像ファイルをカラーで読み込み
src1 = cv2.imread('aloeL.png', cv2.IMREAD_COLOR)
src2 = cv2.imread('aloeR.png', cv2.IMREAD_COLOR)

alpha = 0.5
beta = 0.5
gamma = 0.0

# ピクセルごとに重み付け合成を行う
dst = cv2.addWeighted(src1, alpha, src2, beta, gamma)

# 画像をウィンドウ表示する
cv2.imshow('dst', dst)


In [18]:
x = np.uint8([[10]])
y = np.uint8([[20]])
z = cv2.subtract(x, y)
print(z)

[[0]]


In [ ]:
import numpy as np
import cv2

# 画像ファイルをカラーで読み込み
src1 = cv2.imread('yorkie.png', cv2.IMREAD_COLOR)

# マスク画像を生成する
height, width, channels = src1.shape[:3]
src2 = np.zeros((height, width, channels), np.uint8)
cv2.rectangle(src2, (150, 135), (290, 315), (155, 155, 155), thickness=-1)#thicknessは、ある種の線の太さのようなもの.-1は無限ってことで、塗りつぶしになる

# ピクセルごとにAND演算を行う
dst = cv2.bitwise_and(src1, src2)#and演算、255の場合11111111になるので、元画像をすべて通すことになる1,1=1 1,0=0

# 画像をウィンドウ表示する
cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
import numpy as np
import cv2

# 画像ファイルをカラーで読み込み
src1 = cv2.imread('yorkie.png', cv2.IMREAD_COLOR)

# マスク画像を生成する
height, width, channels = src1.shape[:3]
src2 = np.zeros((height, width, channels), np.uint8)
cv2.rectangle(src2, (150, 135), (290, 315), (255, 255, 255), thickness=-1)

# ピクセルごとにOR演算を行う
dst = cv2.bitwise_or(src1, src2)#0,1=1 0,0=0 1,1=1 1,0=1

# 画像をウィンドウ表示する
cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
import cv2

# 画像ファイルをカラーで読み込み
src1 = cv2.imread('aloeL.png', cv2.IMREAD_COLOR)
src2 = cv2.imread('aloeR.png', cv2.IMREAD_COLOR)

alpha = 0.5
beta = 0.5
gamma = 0.0

# ピクセルごとに重み付け合成を行う
dst = cv2.addWeighted(src1, alpha, src2, beta, gamma)

# 画像をウィンドウ表示する
cv2.imshow('dst', dst)
cv2.waitKey(0)

48

In [33]:
img1 = np.array([[1, 2, 3, 4, 5],[2,1,3,4,5]])
img1.shape


(2, 5)

In [34]:
import numpy as np
import cv2

img1 = np.array([[1, 2, 3, 4, 5]])
img2 = np.array([[5, 4, 3, 2, 1]])

# ピクセルごとに差分の絶対値を計算する
diff = cv2.absdiff(img1, img2)

# abs(1-5) = 4
# abs(2-4) = 2
# abs(3-3) = 0
# abs(4-2) = 4
# abs(5-1) = 2

print(diff)

[[4 2 0 2 4]]


In [ ]:
org_img = cv2.imread('yorkie.png', cv2.IMREAD_COLOR)


mask = np.full(org_img.shape, 255, np.uint8)
cv_copy_img = cv2.copyTo(org_img, mask)#コピーするかしないかの、判断座標になっていて、255の座標はコピーする、0の座標はコピーしないということになる

# numpy.ndarray.copyでコピーする
numpy_copy_img = org_img.copy()

# shallow copyでコピーする
shallow_copy_img = org_img

# コピー元（img1）の左上を矩形で塗りつぶす
cv2.rectangle(org_img, (0, 0), (100, 100), (255, 255, 255), thickness=-1)

# 画像をウィンドウ表示する
cv2.imshow('cv_copy_img', cv_copy_img)
cv2.imshow('numpy_copy_img', numpy_copy_img)
cv2.imshow('shallow_copy_img', shallow_copy_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [39]:

# 画像ファイルをカラーで読み込み
src = cv2.imread('yorkie.png', cv2.IMREAD_COLOR)

# X軸を中心に反転
dst = cv2.flip(src, 1)

# 画像をウィンドウ表示する
cv2.imshow('src', src)
cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
import cv2

# 画像ファイルをカラーで読み込み
src = cv2.imread('yorkie.png', cv2.IMREAD_COLOR)

# 画像原点O(0, 0)を中心にして画像を時計回りに90度回転
rotated = cv2.rotate(src, cv2.ROTATE_90_CLOCKWISE)

# 画像をウィンドウ表示する
cv2.imshow('src', src)
cv2.imshow('rotated', rotated)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [42]:
import numpy as np
import cv2

img = np.array([[0, 1, 2, 3, 4, 5, 6]])

# 1から5の範囲で値をクリッピングする
clip1 = img.clip(1, 5)
print(f'clip1 = {clip1}')

# 最大値を5として値をクリッピングする
clip2 = img.clip(None, 5)
print(f'clip2 = {clip2}')

clip1 = [[1 1 2 3 4 5 5]]
clip2 = [[0 1 2 3 4 5 5]]


In [43]:
import numpy as np
import cv2

img = np.array([[1, 2, 3, 4, 5]])

# 画像データ中の画素値の最小値を求める
min = img.min()

# 画像データ中の画素値の最大値を求める
max = img.max()

print(f'min = {min}, max = {max}')

min = 1, max = 5


In [44]:
import numpy as np
import cv2

img = np.array([[1, 2, 3],  [4, 5, 6]])

# 画像データ中における画素値の最小値、最大値、
# 画素値が最小となる座標、画素値が最大となる画素の座標を求める
min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(img)

print(f'min_val = {min_val}')
print(f'max_val = {max_val}')
print(f'min_loc = {min_loc}')
print(f'max_loc = {max_loc}')

min_val = 1.0
max_val = 6.0
min_loc = (0, 0)
max_loc = (2, 1)


In [6]:
img=cv2.imread('yorkie.png', cv2.IMREAD_COLOR)
b,g,r=cv2.split(img)#b,g,rの順番で分割される
cv2.imshow('Blue Channel', b)

In [8]:
import cv2
gazou=cv2.merge([b,g,r])
cv2.imshow('Merged Image', gazou)
cv2.waitKey(0)

-1

In [9]:
import cv2

# 画像ファイルをカラーで読み込み
img1 = cv2.imread('yorkie.png', cv2.IMREAD_COLOR)
img2 = cv2.imread('yorkie_flip_0.png', cv2.IMREAD_COLOR)

# 画像を水平方向に連結
hconcat_img = cv2.hconcat([img1, img2])

# 画像をウィンドウ表示する
cv2.imshow('img1', img1)
cv2.imshow('img2', img2)
cv2.imshow('hconcat_img', hconcat_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
import numpy as np
import cv2

# 画像ファイルをカラーで読み込み
img1 = cv2.imread('yorkie.png', cv2.IMREAD_COLOR)
img2 = cv2.imread('yorkie_flip_0.png', cv2.IMREAD_COLOR)

# 画像を垂直方向に連結
vconcat_img = cv2.vconcat([img1, img2])

cv2.imshow('img1', img1)
cv2.imshow('img2', img2)
cv2.imshow('vconcat_img', vconcat_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
import cv2

print(cv2.getBuildInformation())


General configuration for OpenCV 4.12.0 =====================================
  Version control:               47f1dd6-dirty

  Extra modules:
    Location (extra):            /home/conda/feedstock_root/build_artifacts/libopencv_1766492611066/work/opencv_contrib/modules
    Version control (extra):     47f1dd6-dirty

  Platform:
    Timestamp:                   2025-12-23T12:27:55Z
    Host:                        Linux 6.11.0-1018-azure x86_64
    CMake:                       4.2.1
    CMake generator:             Ninja
    CMake build tool:            /home/conda/feedstock_root/build_artifacts/libopencv_1766492611066/_build_env/bin/ninja
    Configuration:               Release
    Algorithm Hint:              ALGO_HINT_ACCURATE

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (17 files):         + SSSE3 SSE4_1
      SSE4_2 (1 files):          

In [13]:
import cv2

# 画像ファイルをカラーで読み込み
img = cv2.imread('yorkie.png', cv2.IMREAD_COLOR)

# cv2.TickMeterクラスのインスタンスを生成
timer = cv2.TickMeter()

# 処理時間計測開始
timer.start()

# 計測したい処理（グレースケール変換）
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 処理時間計測終了
timer.stop()

# 計測結果をミリ秒単位にして取得
measurement_time = timer.getTimeMilli()

print(f"measurement_time = {measurement_time:.3f}[ms]")

measurement_time = 15.044[ms]


In [16]:
cv2.imshow('img', gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
import cv2

# 画像ファイルをカラーで読み込み
img = cv2.imread('yorkie.png', cv2.IMREAD_COLOR)

# cv2.TickMeterクラスのインスタンスを生成
timer = cv2.TickMeter()

for i in range(5):
    # タイマーをリセット
    timer.reset()

    # 処理時間計測開始
    timer.start()

    # 計測したい処理（グレースケール変換）
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # 処理時間計測終了
    timer.stop()

    # 計測結果をミリ秒単位にして取得
    measurement_time = timer.getTimeMilli()
    print(f"measurement_time = {measurement_time:.3f}[ms]")

measurement_time = 7.647[ms]
measurement_time = 3.699[ms]
measurement_time = 7.967[ms]
measurement_time = 7.969[ms]
measurement_time = 7.979[ms]


In [20]:
import sys
import numpy as np
import cv2

# ファイル名
filename = 'output.xml'

# 書き込みモードでファイルを開く
fs = cv2.FileStorage(filename, cv2.FileStorage_WRITE)

## 以下のような書き方でもよい
## fs = cv2.FileStorage()
## fs.open(filename, cv2.FileStorage_WRITE)

# ファイルのオープンに失敗したらエラーとして終了
if fs.isOpened() is False:
    print('Failed to load XML file.')
    sys.exit(1)

# 書き出したいデータを定義
R = np.eye(3, 3)
T = np.zeros((3, 1))

# 書き出し
fs.write('R_MAT', R)
fs.write('T_MAT', T)

# コメント追記
fs.writeComment('This is comment')

# ファイルのクローズ、バッファの解放
fs.release()

In [21]:
import sys
import numpy as np
import cv2

# ファイル名
filename = 'input.xml'

# 読み込みモードでファイルを開く
fs = cv2.FileStorage(filename, cv2.FileStorage_READ)

## 以下のような書き方でもよい
## fs = cv2.FileStorage()
## fs.open(filename, cv2.FileStorage_READ)

# ファイルのオープンに失敗したらエラーとして終了
if fs.isOpened() is False:
    print('Failed to load XML file.')
    sys.exit(1)

# 要素の読み込み
R = fs.getNode('R_MAT').mat()
T = fs.getNode('T_MAT').mat()

print(R)
print(T)

# ファイルのクローズ、バッファの解放
fs.release()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.]
 [0.]
 [0.]]


In [22]:
import cv2



cv2.useOptimized()

True

In [23]:
import cv2

print(f'before: {cv2.useOptimized()}')
cv2.setUseOptimized(False)
print(f'after: {cv2.useOptimized()}')

before: True
after: False
